server:
  port: 9002

spring:
  application:
    name: order-consumer
eureka:
  client:
    #表示向注册中心注册自己 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版：defaultZone: http://localhost:7001/eureka/ # 入驻地址
      defaultZone: http://eureka7001:7001/eureka/ # 入驻地址
logging:
  level:
    com.chy.springcloud.service.ConsumerService: debug
feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。

