server:
  port: 8007

spring:
  application:
    name: payment-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root1234

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.chy.springcloud.entities

eureka:
  client:
    #表示向注册中心注册自己 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka # 入驻地址，
  instance:
    instance-id: payment8007
    prefer-ip-address: true
      #Eureka客户端向服务端发送心跳的时间间隔,默认是30s
    lease-renewal-interval-in-seconds: 1
      #Eureka服务端在收到最后一次心跳后等待时间上限,单位为秒(默认是90s),超时将剔除服务
    lease-expiration-duration-in-seconds: 2