server:
  port: 8888
spring:
  application:
    name: gateway8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
         # uri: http://localhost:9001 #匹配后提供服务的路由地址
          uri: lb://PAYMENT-PROVIDER  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          uri: lb://PAYMENT-PROVIDER
          predicates:
            - Path=/payment/discovery   #断言,路径相匹配的进行路由
eureka:
  instance:
    hostname: gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001:7001/eureka
